site_name: Basic MkDocs Example Project
site_url: https://test-docs-ufpy.readthedocs.io/en/latest/
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
